# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33ba9a942d3f8a2aa9d20211472c3c2b8c1f34efc5076848e04e9d216b827715ca5eb5c934e6c1087fa5bab3ebc1f00d06a14a0ca15d21498f4310eec492b688

test:
  secret_key_base: 6bca1bde0d5d31141811d430d77444afdce4c6ed8e3b098feab0596b094bc9462cd7fb381585ffc5c50fd518394c3bde1d4c963ea2d55bc94d2d2b7c08aefcf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
